// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW00iulWKTdpaeHnVm5TNqyYHR881WBk8',
    appId: '1:790912195650:web:d2370fa76901b1ffa221db',
    messagingSenderId: '790912195650',
    projectId: 'greeny-6b1c0',
    authDomain: 'greeny-6b1c0.firebaseapp.com',
    databaseURL: 'https://greeny-6b1c0-default-rtdb.firebaseio.com',
    storageBucket: 'greeny-6b1c0.appspot.com',
    measurementId: 'G-21G482NKBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlB1F9sCJfSr47PwSJCeP9GpG4RTpugc',
    appId: '1:790912195650:android:bbddff4dd2fb18a4a221db',
    messagingSenderId: '790912195650',
    projectId: 'greeny-6b1c0',
    databaseURL: 'https://greeny-6b1c0-default-rtdb.firebaseio.com',
    storageBucket: 'greeny-6b1c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiGSSA3HK_Ctvg5VjHV-06UHPMZNS3dKo',
    appId: '1:790912195650:ios:a44ec9164dcdbf7aa221db',
    messagingSenderId: '790912195650',
    projectId: 'greeny-6b1c0',
    databaseURL: 'https://greeny-6b1c0-default-rtdb.firebaseio.com',
    storageBucket: 'greeny-6b1c0.appspot.com',
    iosBundleId: 'com.example.myOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiGSSA3HK_Ctvg5VjHV-06UHPMZNS3dKo',
    appId: '1:790912195650:ios:a44ec9164dcdbf7aa221db',
    messagingSenderId: '790912195650',
    projectId: 'greeny-6b1c0',
    databaseURL: 'https://greeny-6b1c0-default-rtdb.firebaseio.com',
    storageBucket: 'greeny-6b1c0.appspot.com',
    iosBundleId: 'com.example.myOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW00iulWKTdpaeHnVm5TNqyYHR881WBk8',
    appId: '1:790912195650:web:d25451b4516526c6a221db',
    messagingSenderId: '790912195650',
    projectId: 'greeny-6b1c0',
    authDomain: 'greeny-6b1c0.firebaseapp.com',
    databaseURL: 'https://greeny-6b1c0-default-rtdb.firebaseio.com',
    storageBucket: 'greeny-6b1c0.appspot.com',
    measurementId: 'G-PLP21JVXG4',
  );
}
